#!/usr/bin/bash

# Attemp to Terminate and Remove previous session
if [ -f kaga.session ]; then
    kill $(pgrep -f 'python3 -m kaga')
    rm -f kaga.session-journal kaga.session
fi

# start
python3 -m kaga
