# Taken from Openuserbot.
GDNIGHT = [
    "`Selamat malam menjaga impianmu tetap hidup",
    "`Malam, malam, untuk teman tersayang! Semoga tidur nyenyak!`",
    "`Semoga malam penuh dengan bintang-bintang untukmu. Semoga menghitung setiap orang, memberi Anda puas!`",
    "`Berharap anda nyaman, bahagia, dan tidur nyenyak!`",
    "`Sekarang santai saja. Hari sudah berakhir. Anda melakukan yang terbaik. Dan besok anda akan melakukan yang lebih baik. Selamat malam!`",
    "`Selamat malam untuk teman yang terbaik! Dapatkan empat puluh kedi mata Anda!`",
    "`Semoga bantalmu lembut, dan istirahatmu panjang! Selamat malam, teman!`",
    "`Biar tidak ada masalah, teman tersayang! Selamat malam!`",
    "`Istirahatlah dengan nyenyak malam ini, teman!`",
    "Tidurlah malam terbaik, teman! Tidur nyenyak!`",
    "`Semoga malammu menyenangkan, teman! Anda luar biasa!`",
    "`Relaksasi adalah dalam rangka untuk Anda! Selamat malam, teman!`",
    "`Selamat malam. Semoga Anda memiliki mimpi indah malam ini.`",
    "`Tidur nyenyak, sayang teman dan memiliki mimpi manis.`",
    "`Saat kita menunggu hari baru, selamat malam dan memiliki mimpi indah.`",
    "`Sahabat terkasih, saya ucapkan selamat malam yang damai dan bahagia. Selamat malam.`",
    "`Kegelapan tidak bisa bertahan selamanya. Jaga harapan tetap hidup. Selamat malam.`",
    "`Dengan hook atau penjahat Anda akan memiliki mimpi manis malam ini. Semoga malammu menyenangkan, sobat!`",
    "`Selamat malam, teman saya. Saya berdoa agar Tuhan yang baik mengawasi Anda saat Anda tidur. Mimpi indah.`",
    "`Selamat malam, teman! Semoga anda dipenuhi dengan ketenangan!`",
    "`Berharap malam yang tenang, teman! Saya berharap itu baik!`",
    "`Berharap Anda malam di mana Anda dapat mengisi ulang untuk besok!`",
    "Tertidur malam ini, teman baik, dan merasa beristirahat dengan baik, besok!`",
    "`Berharap teman baik saya lega dari kerja keras seharian! Selamat malam!`",
    "`Selamat malam, teman! Semoga Anda memiliki keheningan untuk tidur!`",
    "`Tidurlah malam ini, teman dan sehat! Ketahuilah bahwa Anda telah melakukan yang terbaik hari ini, dan bahwa Anda akan melakukan yang terbaik, besok!`",
    "`Teman, Anda tidak ragu untuk menyelesaikan sesuatu! Ambil malam ini untuk bersantai dan melakukan lebih banyak, besok!`",
    "`Teman, saya ingin mengingatkan Anda bahwa pikiran kuat Anda telah membawa Anda kedamaian, sebelumnya. Semoga itu terjadi lagi, malam ini! Semoga Anda memegang pengakuan ini dengan Anda!`",
    "`Berharap anda tenang, malam, teman! Berharap semuanya berliku sesuai dengan keinginan Anda dan bahwa hari berikutnya memenuhi standar Anda!`",
    "`Semoga kegelapan malam menyelubungi anda dalam tidur yang suara dan baik! Teman terkasih, semoga perasaan ini membawamu keesokan harinya!`",
    "`Teman, semoga ketenangan yang Anda alami malam ini menggerakkan Anda untuk memiliki lebih banyak malam seperti itu! Semoga Anda menemukan kedamaian Anda dan berpegang pada itu!`",
    "`Semoga tidak ada kegiatan untuk anda malam ini, teman! Semoga sisanya bahwa Anda telah datang kepada Anda tiba dengan cepat! Semoga aktivitas yang Anda lakukan besok cocok dengan kecepatan Anda dan menjadi semua yang Anda buat sendiri!`",
    "`Ketika hari selesai, teman, semoga Anda tahu bahwa Anda telah melakukannya dengan baik! Ketika Anda tidur malam ini, teman, semoga Anda melihat semua yang Anda harapkan, besok!`",
    "`Ketika semuanya dihentikan, teman, saya berharap bahwa pikiran Anda baik, saat Anda melayang untuk tidur! Semoga pikiran-pikiran itu tetap bersamamu, selama hari-harimu!`",
    "`Setiap hari, Anda mendorong saya untuk melakukan hal-hal baru, teman! Semoga istirahat malam ini membawa hari baru yang meluap dengan keberanian dan acara-acara menarik!`",
]

# Taken from Openuserbot.
GDMORNING = [
    "`Hidup ini penuh dengan ketidakpastian. Tapi akan selalu ada matahari terbit setelah setiap matahari terbenam. Selamat pagi!`",
    "`Tidak peduli seberapa buruk kemarin anda. Hari ini, anda akan membuatnya menjadi yang baik. Berharap anda selamat pagi!`",
    "`Jika Anda ingin mendapatkan kesehatan dan kecantikan, Anda harus bangun pagi. Selamat pagi!`",
    "`Semoga pagi ini menawarkan harapan baru untuk hidup! Semoga Anda bahagia dan menikmati setiap momen itu. Selamat pagi!`",
    "`Semoga matahari menghujani anda dengan berkah dan kemakmuran di hari-hari ke depan. Selamat pagi!`",
    "`Setiap matahari terbit menandai munculnya kehidupan atas kematian, harapan atas keputusasaan dan kebahagiaan atas penderitaan. Berharap anda pagi yang sangat menyenangkan hari ini!`",
    "`Bangunlah dan jadikan dirimu bagian dari pagi yang indah ini. Dunia yang indah menunggu di luar pintumu. Seiring waktu yang menyenangkan!`",
    "`Selamat datang pagi yang indah ini dengan senyum di wajah anda. Saya harap Anda akan memiliki hari yang besar hari ini. Berharap anda pagi yang sangat baik!`",
    "`Anda telah diberkati dengan hari lain. Sungguh cara yang luar biasa untuk menyambut berkat dengan pagi yang indah! Selamat pagi untuk anda!`",
    "`Bangun di pagi yang indah seperti itu adalah penjaminan untuk hari yang luar biasa. Saya harap Anda akan membuat yang terbaik dari itu. Selamat pagi!`",
    "`Tidak ada yang lebih menyegarkan daripada pagi yang indah yang menenangkan pikiran Anda dan memberi Anda alasan untuk tersenyum. Selamat pagi! Berharap anda hari yang besar.`",
    "`Satu hari lagi baru saja dimulai. Sambutlah berkah pagi yang indah ini. Bangkit dan bersinar seperti yang selalu anda lakukan. Berharap anda pagi yang indah!`",
    "`Bangunlah seperti matahari setiap pagi dan menerangi dunia keangkeran Anda. Anda memiliki begitu banyak hal besar untuk dicapai hari ini. Selamat pagi!`",
    "`Hari baru telah datang dengan begitu banyak peluang baru untuk Anda. Ambil semuanya dan buat yang terbaik dari hari Anda. Ini aku mengucapkan selamat pagi!`",
    "`Kegelapan malam telah berakhir. Matahari baru di atas sana untuk membimbing Anda menuju kehidupan yang begitu cerah dan bahagia. Selamat pagi sayang!`",
    "`Bangunlah, minum secangkir teh pagimu dan biarkan angin pagi menyegarkanmu seperti pil kebahagiaan. Semoga pagimu menyenangkan dan hari yang cerah!`",
    "`Matahari terbit adalah yang terbaik; nikmati secangkir kopi atau teh dengan diri Anda sendiri karena hari ini adalah milikmu, selamat pagi! S memiliki hari yang indah di depan.`",
    "`Hari yang buruk akan selalu memiliki pagi yang baik, berharap semua kekhawatiran Anda hilang dan semua yang Anda inginkan bisa menemukan tempat. Selamat pagi!`",
    "`Akhir yang hebat mungkin tidak diputuskan tetapi awal kreatif yang baik dapat direncanakan dan dicapai. Selamat pagi, semoga harimu produktif!`",
    "`Memiliki pagi yang manis, secangkir kopi, hari dengan orang yang Anda cintai adalah apa yang membuat “Selamat Pagi” Anda memiliki hari yang menyenangkan!`",
    "`Apa pun bisa salah di siang hari tetapi pagi hari harus indah, jadi saya memastikan pagi Anda mulai indah. Selamat pagi!`",
    "`Buka matamu sambil tersenyum, berdoa dan bersyukurlah bahwa kamu bangun sampai awal yang baru. Selamat pagi!`",
    "`Pagi bukan hanya matahari terbit tapi Mukjizat Tuhan yang indah yang mengalahkan kegelapan dan menyebarkan terang. Selamat pagi.`",
    "`Hidup tidak pernah memberimu kesempatan kedua. Jadi, nikmatilah setiap bagiannya. Mengapa tidak mulai dengan pagi yang indah ini. Selamat pagi!`",
    "`Jika Anda ingin mendapatkan kesehatan dan kecantikan, Anda harus bangun pagi. Selamat pagi!`",
    "`Burung menyanyikan melodi manis dan angin sepoi-sepoi bertiup melalui pepohonan, pagi yang sempurna untuk membangunkan Anda. Selamat pagi!`",
    "`Pagi ini sangat santai dan indah sehingga saya benar-benar tidak ingin Anda melewatkannya dengan cara apa pun. Jadi, bangunlah teman tersayang. Selamat pagi untukmu!`",
    "`Pagi-pagi datang dengan kanvas kosong. Cat sesering yang Anda suka dan menyebutnya hari. Bangun sekarang dan mulailah menciptakan hari yang sempurna. Selamat pagi!`",
    "`Setiap pagi membawa harapan baru dan peluang baru. Jangan lewatkan salah satu dari mereka saat anda sedang tidur. Selamat pagi!`",
    "`Mulailah hari Anda dengan tekad yang solid dan sikap yang hebat. Anda akan memiliki hari yang baik hari ini. Selamat pagi teman saya!`",
    "`Persahabatan itulah yang membuat hidup layak untuk hidup. Saya ingin mengucapkan terima kasih untuk menjadi teman khusus saya. Selamat pagi untuk anda!`",
    "`Seorang teman sepertimu cukup sulit untuk datang dalam hidup. Aku harus menganggap diriku cukup beruntung memilikimu. Selamat pagi. Berharap Anda hari yang menakjubkan di depan!`",
    "`Semakin Anda menghitung diri Anda sebagai diberkati, semakin diberkati Anda akan. Alhamdulillah pagi yang indah ini dan biarkan persahabatan dan cinta menang pagi ini.`",
    "`Bangun dan menyesap secangkir persahabatan yang penuh kasih. Makan hatimu dari sepiring harapan. Untuk top it up, garpu penuh kebaikan dan cinta. Cukup untuk selamat pagi!`",
    "`Sangat mudah membayangkan dunia akan segera berakhir. Tapi sulit membayangkan menghabiskan hari tanpa teman-temanku. Selamat pagi.`",
]

# Abuse strings credits @NotAMemeBot
ABUSE_STRINGS = (
    "Enyahlah",
    "Diam pergi bercinta sendiri",
    "Anda noob",
    "Rilekskan Belakangmu, jangan takut, Kereta pemerkosaan akhirnya ada di sini",
    "diam kau",
    "diam dan kamu itu nub",
    "Vagina",
    "Gay ada di sini",
    "Owww ... Seperti idiot bodoh.",
    "Jangan minum dan mengetik.",
    "Saya pikir Anda harus pulang atau lebih baik rumah sakit jiwa.",
    "Komando tidak ditemukan. Sama seperti otakmu.",
    "Apakah Anda menyadari Anda membuat bodoh diri sendiri? Rupanya tidak.",
    "Kau bisa mengetik lebih baik dari itu.",
    "Aturan bot 544 bagian 9 mencegah saya membalas manusia bodoh seperti Anda.",
    "Maaf, kami tidak menjual otak.",
    "Percayalah kau tidak normal.",
    "Saya yakin otak Anda terasa sebagus baru, melihat bahwa Anda tidak pernah menggunakannya.",
    "Jika aku ingin bunuh diri aku akan memanjat egomu dan melompat ke IQ-nya.",
    "Zombie memakan otak... Anda aman.",
    "Anda tidak berevolusi dari kera, mereka berevolusi dari Anda.",
    "Kembalilah dan bicaralah padaku saat IQ-nya melebihi usiamu.",
    "Saya tidak mengatakan Anda bodoh, saya hanya mengatakan Anda punya nasib buruk ketika datang ke berpikir.",
    "Bahasa apa yang anda bicarakan? Karena kedengarannya seperti omong kosong.",
    "Kebodohan bukanlah kejahatan sehingga Anda bebas untuk pergi.",
    "Anda adalah bukti bahwa evolusi BISA berbalik.",
    "Saya akan bertanya berapa usia Anda tapi saya tahu Anda tidak bisa menghitung setinggi itu.",
    "Sebagai orang luar, apa pendapatmu tentang umat manusia?",
    "Otak bukanlah segalanya. Dalam kasus Anda mereka bukan apa-apa.",
    "Biasanya orang hidup dan belajar. Anda hanya hidup.",
    "Aku tidak tahu apa yang membuatmu begitu bodoh, tapi itu benar-benar berhasil.",
    "Teruslah bicara, suatu hari nanti kamu akan mengatakan sesuatu yang cerdas! (Aku meragukannya)",
    "Shock saya, mengatakan sesuatu yang cerdas.",
    "IQ-mu lebih rendah dari ukuran sepatumu.",
    "Alangkah besarnya penyesalan terhadap hamba-hamba Neurotransmiter anda tidak lebih bekerja.",
    "Apakah Anda gila Anda bodoh.",
    "Setiap orang memiliki hak untuk menjadi bodoh tetapi Anda menyalahgunakan hak istimewa.",
    "Maaf aku menyakiti perasaanmu saat aku memanggilmu bodoh. Kupikir kau sudah tahu itu.",
    "Anda harus mencoba mencicipi sianida.",
    "Enzimmu dimaksudkan untuk mencerna racun tikus.",
    "Anda harus mencoba tidur selamanya.",
    "Ambil pistol dan tembak dirimu sendiri.",
    "Anda bisa membuat rekor dunia dengan melompat dari pesawat tanpa parasut.",
    "Berhenti bicara BS dan melompat di depan kereta peluru yang sedang berjalan.",
    "Cobalah mandi dengan Asam Klorida alih-alih air.",
    "Cobalah ini: jika Anda menahan napas di bawah air selama satu jam, Anda kemudian dapat menahannya selamanya.",
    "Go Green! Berhenti menghirup Oksigen.",
    "Tuhan sedang mencarimu. Anda harus pergi untuk bertemu dengannya.",
    "Berikan 100%. Sekarang, pergi menyumbangkan darah.",
    "Cobalah melompat dari seratus bangunan cerita tetapi Anda dapat melakukannya hanya sekali.",
    "Anda harus menyumbangkan otak Anda melihat bahwa Anda tidak pernah menggunakannya.",
    "Sukarelawan untuk target dalam jarak tembak.",
    "Sundulannya menyenangkan. Dapatkan diri Anda satu.",
    "Anda harus mencoba berenang dengan hiu putih besar.",
    "Anda harus melukis diri Anda merah dan berlari dalam maraton banteng.",
    "Anda dapat tinggal di bawah air selama sisa hidup Anda tanpa datang kembali.",
    "Bagaimana kalau kau berhenti bernapas selama 1 hari? Itu akan menjadi besar.",
    "Cobalah memprovokasi harimau saat kalian berdua berada di kandang.",
    "Apakah Anda mencoba menembak diri sendiri setinggi 100m menggunakan kanon.",
    "Anda harus mencoba memegang TNT di mulut Anda dan menyalakannya.",
    "Cobalah bermain menangkap dan melempar dengan RDX kesenangannya.",
    "Saya mendengar foorin beracun tetapi saya kira Anda tidak akan keberatan menghirupnya untuk bersenang-senang.",
    "Luncurkan diri anda ke luar angkasa sambil melupakan oksigen di Bumi.",
    "Anda harus mencoba bermain ular dan tangga, dengan ular nyata dan tidak ada tangga.",
    "Menari telanjang di beberapa kabel HT.",
    "Gunung Berapi Aktif adalah kolam renang terbaik untuk Anda.",
    "Anda harus mencoba mandi air panas di gunung berapi.",
    "Cobalah untuk menghabiskan satu hari dalam peti mati dan itu akan menjadi milikmu selamanya.",
    "Pukul Uranium dengan neutron bergerak lambat di hadapanmu. Ini akan menjadi pengalaman yang berharga.",
    "Anda bisa menjadi orang pertama yang menginjak matahari. Cobalah.",
)

RUN_STRINGS = (
    "Mau kemana?",
    "Ya? Apa? Apakah mereka lolos?",
    "Zzzzzzzz... Ya? Apa? oh, hanya mereka lagi, sudahlah.",
    "Kembali ke sini!",
    "Tidak begitu cepat...",
    "Ayilah dinding!",
    "Jangan tinggalkan aku sendirian dengan mereka!!",
    "Anda berlari, Anda mati.",
    "Lelucon padamu, aku ada dimana-mana",
    "Kau akan menyesalinya...",
    "Anda juga bisa mencoba / kickme, saya mendengar itu menyenangkan." ,
    "Pergi mengganggu orang lain, tidak ada seorang pun di sini peduli.",
    "Kau bisa lari, tapi kau tak bisa sembunyi.",
    "Hanya itu yang kau punya?",
    "Aku di belakangmu...",
    "Anda punya perusahaan!",
    "Kita bisa melakukan ini dengan cara yang mudah, atau dengan cara yang sulit.",
    "Anda hanya tidak mendapatkannya, kan?",
    "Ya, sebaiknya kau lari!",
    "Tolong, ingatkan aku betapa aku peduli?",
    "Aku akan berlari lebih cepat jika aku jadi kau.",
    "Itu pasti droid yang kita cari.",
    "Semoga peluangnya selalu menguntungkanmu.",
    "Kata-kata terakhir yang terkenal.",
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi."
    "Oh, lihat aku! Aku sangat keren, aku bisa lari dari bot!"
    "Ya ya, cukup ketuk /kickme sudah.",
    "Di sini, ambil cincin ini dan menuju ke Mordor saat Anda berada di itu."
    "Legenda memilikinya, mereka masih berjalan ...",
    "Tidak seperti Harry Potter, orang tuamu tidak bisa melindungimu dariku.",
    "Ketakutan menyebabkan kemarahan. Kemarahan menyebabkan kebencian. Kebencian menyebabkan penderitaan. Jika Anda terus berjalan dalam ketakutan, Anda mungkin "
    "jadilah Vader berikutnya.",
    "Beberapa perhitungan kemudian, saya telah memutuskan minat saya pada shenanigans Anda adalah tepat 0.",
    "Legenda memilikinya, mereka masih berjalan."
    "Pertahankan, tidak yakin kami tetap ingin kau di sini.",
    "Kau wiza- Oh. Tunggu. Kau bukan Harry, terus bergerak."
    "TIDAK BERJALAN DI LORONG!",
    "Hasta la vista, sayang.",
    "Siapa yang membiarkan anjing keluar?",
    "Ini lucu, karena tidak ada yang peduli.",
    "Ah, sia-sia sekali. Saya menyukai yang satu itu.",
    "Terus terang, sayangku, aku tidak peduli.",
    "Milkshake saya membawa semua anak laki-laki ke halaman ... Jadi larilah lebih cepat!",
    "Anda tidak dapat MENANGANI kebenaran!",
    "Dahulu kala, di galaksi yang jauh... Seseorang pasti peduli tentang itu. Tidak lagi.",
    "Hei, lihat mereka! Mereka lari dari banhammer tak terelakkan... Lucu.",
    "Han menembak duluan. Begitu juga denganku."
    "Apa yang kau jalankan, kelinci putih?",
    "Seperti yang dokter akan katakan... LARI!",
)

# SLAP_TEMPLATES From @SaitamaRobot

SLAP_TEMPLATES = (
    "{user2} ditembak oleh {user1}.",
    "{user2} masuk ke kaktus saat mencoba melarikan diri {user1}.",
    "{user2} tenggelam saat mencoba melarikan diri {user1}.",
    "{user2} jatuh ke dalam sepetak kaktus.",
    "{user2} terbakar."
    "{user2} terbakar sampai mati.",
    "{user2} dibakar hingga garing saat melawan {user1}.",
    "{user2} disambar petir.",
    "{user2} dibunuh oleh {user1}.",
    "{user2} dibunuh oleh sihir.",
    "{user2} mati kelaparan.",
    "{user2} jatuh dari dunia.",
    "{user2} diketuk ke dalam kekosongan oleh {user1}.",
    "{user2}tulang dikerok bersih oleh angin sepi.",
    "{user2} pingsan.",
    "{user2} tidak dapat digunakan Pokemon! [user2} diutihkan!.",
    "{user2} tidak dapat digunakan Pokemon! [user2} pingsan!.",
    "{user2} mengucapkan selamat tinggal pada dunia yang kejam ini.",
    "{user2} mendapat rekt.",
    "{user2} digaji setengah oleh {user1}.",
    "Melon {user2} dibagi oleh {user1}.",
    "{user2} diiris dan dipotong dadu oleh {user1}.",
    "{user2}kematian menempatkan takik lain di sumbu {user1}.",
    "{user2} meninggal karena penyakit tropis misterius {user1}.",
    "{user2} bermain kentang panas dengan granat.",
    "{user2} ditusuk oleh {user1}.",
    "{user2} makan granat.",
    "{user2} adalah apa untuk makan malam!",
    "{user2} dihentikan oleh {user1}.",
    "{user2} ditembak sebelum dibuang dari pesawat.",
    "{user2} mengalami kesalahan.",
    "{user2} mati dan bereinkarnasi sebagai kambing.",
    "{user1} melemparkan {user2} dari sebuah bangunan.",
    "{user2} mendapat penguburan prematur.",
    "{user1} email spam {user2}.",
    "{user1} tekan {user2} dengan pesawat ruang angkasa kecil antarbintang.",
    "{user1} menempatkan {user2} dalam check-mate.",
    "{user1} RSA-encrypted {user2} dan menghapus kunci pribadi.",
    "{user1} menempatkan {user2} di friendzone.",
    "{user1} menampar {user2} dengan permintaan penghapusan DMCA!",
    "{user2} meninggal karena gangren rumah sakit.",
    "{user2} mendapat panggilan rumah dari Dokter {user1}.",
    "{user1} dipenggal {user2}.",
    "{user2} dilempari batu... oleh massa yang marah.",
    "{user1} menggugat celana off {user2}.",
    "{user2} adalah KO'd satu pukulan oleh {user1}.",
    "{user1} mengirim {user2} ke bawah lubang memori.",
    "{user2} adalah kesalahan. - '{user1}' ",
    "{user1} diperiksa {user2} dalam dua gerakan.",
    "{user2} dibuat berlebihan.",
    "{user1} {hits} {user2} dengan kelelawar!.",
    "{user1} {hits} {user2} dengan Tendangan Taijutsu!.",
    "{user1} {hits} {user2} dengan X-Gloves!.",
    "{user1} {hits} {user2} dengan Jet Punch!.",
    "{user1} {hits} {user2} dengan Jet Pistol!.",
    "{user1} {hits} {user2} dengan Amerika Serikat Smash!.",
    "{user1} {hits} {user2} dengan Detroit Smash!.",
    "{user1} {hits} {user2} dengan Texas Smash!.",
    "{user1} {hits} {user2} dengan California Smash!.",
    "{user1} {hits} {user2} dengan New Hampshire Smash!.",
    "{user1} {hits} {user2} dengan Missouri Smash!.",
    "{user1} {hits} {user2} dengan Carolina Smash!.",
    "{user1} {hits} {user2} dengan King Kong Gun!.",
    "{user1} {hits} {user2} dengan tongkat baseball - metal one.!.",
    "*Pukulan serius {user2}*.",
    "*Pukulan normal {user2}*.",
    "*Pukulan Normal Berturut-turut {user2}*.",
    "*Dua Tangan Berturut-turut Pukulan Normal {user2}*.",
    "*Mengabaikan {user2} untuk membiarkan mereka mati karena embarassment*.",
    "*poin di {user2}* Ada apa dengan lancang ini... anak hilang?.",
    "*Hits {user2} dengan Fire Tornado*.",
    "{user1} menyodok {user2} di mata !",
    "{user1} menyodok {user2} di samping!",
    "{user1} menyodok {user2}!",
    "{user1} menyodok {user2} dengan jarum!",
    "{user1} menyodok {user2} dengan pena!",
    "{user1} menyodok {user2} dengan pistol setrum!",
    "{user2} diam-diam berbulu!.",
    "Hei semuanya! [user1} meminta saya untuk menjadi jahat!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Ambil ini {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Sini {user2} pengang ini\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2},Shinaeeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Semprotan serangga {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} Anda hama!",
    r"( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "[user1] [hits] {user2} dengan {item}.",
    "{user1} {hits} {user2} di wajah dengan {item}.",
    "{user1} {hits} {user2} sekitar sedikit dengan {item}.",
    "{user1} {throws} a {item} di {user2}.",
    "{user1} meraih {item} dan {throws} di wajah {user2}.",
    "{user1} meluncurkan {item} dalam arah umum {user2}.",
    "{user1} mulai menampar {user2} konyol dengan {item}.",
    "{user1} menyematkan {user2} ke bawah dan berulang kali {hits} mereka dengan {item}.",
    "{user1} meraih {item} dan {hits} {user2} dengannya.",
    "{user1} mengikat {user2} ke kursi dan {throws} a {item} pada mereka.",
    "{user1} memberikan dorongan ramah untuk membantu {user2} belajar berenang di lava.",
    "{user1} di-bully {user2}.",
    "Nyaan memakan kaki {user2}. *nomnomnom*",
    "{user1} {throws} sebuah master ball di {user2}, resistance sia-sia.",
    "{user1} hits {user2} dengan balok aksi... bbbbbb (ง・ω・)ง ===*",
    "{user1} ara ara 's {user2}.",
    "{user1} ora ora {user2}.",
    "{user1} muda muda {user2}.",
    "{user2} diubah menjadi referensi Jojo!",
    "{user1} hits {user2} dengan {item}.",
    "Ronde 2!.. Siap?.. LAWANLAH!!",
)

ITEMS = (
    "wajan besi",
    "mengeong marah",
    "Kelelawar kriket",
    "tongkat kayu",
    "Sekop",
    "Pemanggang roti",
    "Buku",
    "Laptop",
    "ayam karet",
    "kelelawar berduri",
    "Batu berat",
    "bongkahan kotoran",
    "Ton batu bata",
    "rasengan",
    "Bom roh",
    "100-Jenis Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "Larangan",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "kat terbang bulat",
)

THROW = (
    "melempar",
    "melemparkan",
    "membuang",
    "melemparkan",
)

HIT = (
    "hits",
    "mendera",
    "tamparan",
    "pukulan",
    "bashes",
    "tepukan",
)

PUNCH_TEMPLATES = (
    "{user1} {punches} {user2} dengan {item}.",
    "{user1} {punches} {user2} di wajah dengan {item}.",
    "{user1} {punches} {user2} sekitar sedikit dengan {item}.",
    "{user1} {punches} {user2} di wajah mereka. 👊",
)

HUG_TEMPLATES = (
    "{user1} {hug} {user2}.",
    "{user1} {hug} {user2} dengan hangat.",
    "{user1} {hug} {user2} dengan cinta. 💘",
    "{user1} {hug} {user2} dengan kebaikan.",
)

PUNCH = (
    "meninju",
    "ditinju",
    "memukul",
)

HUG = ("pelukan", "pelukan", "cium", "cubit")

# Table strings credits: @SaitamaRobot

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "Saya kehabisan meja, akan memesan lebih banyak.",
    "Lakukan beberapa pekerjaan alih-alih tabel flippin.",
)

GBUN = (
    "Waspadalah! Bot-admeme ini dapat gbun Anda langsung dari peta.",
    "Bagaimana jika ada 'a' bukannya 'u' ... 👀",
    "Saya kira Anda lupa ejaan gban mungkin ...?",
    "OK tidak!",
    "Ok boomer.",
    "Jangan menyalahgunakan kekuatan anda noob ...",
    "Tidak, dia terlihat tidak bersalah...",
    "Bersiaplah untuk palu roti global!",
)

DECIDE = ("Ya.", "Tidak.", "Mungkin.", "Tidak.")

# AFK strings credits: PaperPlaneExtended!
AFKRPL = (
    "<b>{}</b> sedang sibuk saat ini. Silakan bicara dalam tas dan ketika mereka kembali Anda hanya bisa memberinya tas!",
    "<b>{}</b> sedang pergi sekarang. Jika Anda membutuhkan sesuatu, tinggalkan pesan setelah bunyi bip:n<code>beeeeeeeeep</code>!",
    "Anda baru saja <b>{}</b>, lain kali bidik lebih baik.",
    "{} akan kembali dalam beberapa menit dan jika tidak...,nwait lebih lama.",
    "Mawar berwarna merah,nViolets berwarna biru,nLeave saya pesan,nAnd {} akan kembali kepada Anda.",
    "Jika Anda belum mengetahuinya,n{} tidak ada di sini.",
    "{} pergi ke arah sanan---->",
    "{} pergi dengan cara ini n<----",
    "{} tidak ada di sini jadi berhenti menulis kepada mereka,atau anda tidak akan menemukan diri anda dengan layar yang penuh dengan pesan anda sendiri.",
    "Hidup ini sangat singkat, ada begitu banyak hal yang harus dilakukan... n{} sedang pergi melakukan salah satu dari mereka ..",
    "{} jauh dari keyboard saat ini, tetapi jika Anda akan berteriak cukup keras di layar Anda, mereka mungkin hanya mendengar Anda.",
)

NOAFK = (
    "{} ada di sini!",
    "{} kembali!",
    "{} sekarang ada di obrolan!",
    "{} terjaga!",
    "{} kembali online!",
    "{} akhirnya ada di sini!",
    "Selamat datang kembali! {}",
    "OwO {} ada di sini!",
)

AFK = (
    "Cya 👋 {}!",
    "Byebye {}.",
    "Sampai nanti {}!",
    "Selamat tinggal {}!",
    "Kembalilah segera {}!",
    "Kthnxbye {}..",
)

SHGS = (
    "┐(´д｀)┌",
    "┐(´～｀)┌",
    "┐(´ー｀)┌",
    "┐(￣ヘ￣)┌",
    "╮(╯∀╰)╭",
    "╮(╯_╰)╭",
    "┐(´д`)┌",
    "┐(´∀｀)┌",
    "ʅ(́◡◝)ʃ",
    "┐(ﾟ～ﾟ)┌",
    "┐('д')┌",
    "┐(‘～`;)┌",
    "ヘ(´－｀;)ヘ",
    "┐( -“-)┌",
    "ʅ（´◔౪◔）ʃ",
    "ヽ(゜～゜o)ノ",
    "ヽ(~～~ )ノ",
    "┐(~ー~;)┌",
    "┐(-。ー;)┌",
    r"¯\_(ツ)_/¯",
    r"¯\_(⊙_ʖ⊙)_/¯",
    r"¯\_༼ ಥ ‿ ಥ ༽_/¯",
    "乁( ⁰͡  Ĺ̯ ⁰͡ ) ㄏ",
)

CRI = (
    "أ‿أ",
    "╥﹏╥",
    "(;﹏;)",
    "(ToT)",
    "(┳Д┳)",
    "(ಥ﹏ಥ)",
    "（；へ：）",
    "(T＿T)",
    "（πーπ）",
    "(Ｔ▽Ｔ)",
    "(⋟﹏⋞)",
    "（ｉДｉ）",
    "(´Д⊂ヽ",
    "(;Д;)",
    "（>﹏<）",
    "(TдT)",
    "(つ﹏⊂)",
    "༼☯﹏☯༽",
    "(ノ﹏ヽ)",
    "(ノAヽ)",
    "(╥_╥)",
    "(T⌓T)",
    "(༎ຶ⌑༎ຶ)",
    "(☍﹏⁰)｡",
    "(ಥ_ʖಥ)",
    "(つд⊂)",
    "(≖͞_≖̥)",
    "(இ﹏இ`｡)",
    "༼ಢ_ಢ༽",
    "༼ ༎ຶ ෴ ༎ຶ༽",
)

POLICE = [
    "🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵\n🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵\n🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵",
    "🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴\n🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴\n🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴",
    "🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵\n🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵\n🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵",
    "🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴\n🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴\n🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴",
    "🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵\n🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵\n🔴🔴🔴⬜️⬜️⬜️🔵🔵🔵",
    "🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴\n🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴\n🔵🔵🔵⬜️⬜️⬜️🔴🔴🔴",
    "*Police iz Here*",
]


BEING_LOGICAL = (
    "Gelembung bawah air dan tetesan hujan adalah kebalikan dari satu sama lain."
    "Jika Anda membeli penghapus, Anda benar-benar membayar kesalahan Anda."
    "manusia menjajah bulan, itu mungkin akan menarik rumah pensiun karena gravitasi yang lebih lemah akan memungkinkan orang tua untuk merasa lebih kuat.",
    "Orang yang paling kau sayangi memiliki potensi untuk menghancurkanmu."
    "Setiap video dengan “tunggu” dalam judul terlalu lama.",
    "Usiamu bertahun-tahun adalah berapa kali kau mengelilingi Matahari, tapi usiamu dalam beberapa bulan adalah berapa kali Bulan telah mengelilingimu.",
    "Menggigit lidah Anda saat makan adalah contoh sempurna tentang bagaimana Anda masih bisa mengacaukan, bahkan dengan pengalaman puluhan tahun.",
    "Mengatakan bahwa rumah Anda ditenagai oleh reaktor fusi Nuklir nirkabel yang berjarak 93 Juta mil jauhnya terdengar jauh lebih keren daripada hanya mengatakan Anda memiliki panel surya di atap Anda.",
    "Perasaan yang paling menghancurkan adalah ketika seseorang tersenyum pada Anda di jalan dan Anda tidak bereaksi cukup cepat untuk tersenyum kembali."
    "Gigi terus-menerus membutuhkan pemeliharaan untuk mencegah pembusukan mereka ketika hidup, namun mereka berhasil bertahan hidup selama ribuan tahun yang dikubur sebagai fosil.",
    "Folder adalah untuk hal-hal yang tidak ingin Anda lipat.",
    "Bangun di pagi hari kadang-kadang terasa seperti melanjutkan film menyebalkan Anda memutuskan untuk berhenti menonton."
    "Jika semuanya berjalan lancar, Anda mungkin tidak akan ingat hari ini.",
    "Ketika Anda bertemu orang baru dalam kehidupan nyata, Anda membuka lebih banyak karakter untuk dunia impian Anda."
    "Mungkin jika mereka mengganti nama tabir surya menjadi “krim anti-kanker” lebih banyak orang akan memakainya.",
    "200 tahun yang lalu, orang tidak akan pernah menduga bahwa manusia di masa depan akan berkomunikasi dengan diam-diam mengetuk kaca.",
    "Orang tua khawatir tentang apa yang putra mereka unduh dan khawatir tentang apa yang diunggah putri mereka.",
    "Ini gila bagaimana Anda bisa seumuran dengan seseorang, tetapi pada tahap yang sama sekali berbeda dalam hidup Anda."
    "Ketika Anda berpikir Anda ingin mati, Anda benar-benar tidak ingin mati, Anda hanya tidak ingin hidup seperti ini."
    "Secara teknis, tidak ada yang pernah berada di ruangan kosong."
    "Bawang adalah pemain bass makanan. Anda mungkin tidak akan menikmatinya sendirian, tetapi Anda akan merindukannya jika tidak ada di sana."
    "Kami berlari ke mana-mana dalam videogame karena kami terlalu malas untuk berjalan, tetapi Dalam kehidupan nyata kami berjalan di mana-mana karena kami terlalu malas untuk berlari.",
    "Setiap keputusan yang pernah anda buat telah membawa Anda untuk membaca kalimat ini."
    "Kata 'tenang' sering dikatakan sangat keras.",
    "Semua orang ingin anda bekerja keras, tapi tidak ada yang ingin mendengar tentang seberapa keras Anda bekerja."
    "Kami menyikat gigi dengan rambut di tongkat dan menyikat rambut kami dengan gigi di tongkat.",
    "Tidak ada yang ingat saat-saat canggung Anda tetapi mereka terlalu sibuk mengingat mereka sendiri."
    "Orang-orang bodoh mencoba mengatakan ide-ide sederhana sekuleks mungkin sementara orang-orang pintar mencoba mengatakan ide-ide kompleks sesederhana mungkin.",
    "Beberapa orang berpikir mereka lebih baik darimu karena mereka tumbuh lebih kaya. Beberapa orang berpikir mereka lebih baik darimu karena mereka tumbuh lebih miskin."
    "Ironi terbesar adalah bahwa komputer &amp; ponsel diciptakan untuk menghemat waktu!",
    "Setelah madu pertama kali ditemukan, kemungkinan ada periode di mana orang-orang sedang menguji lendir yang tersedia dari serangga.",
    "Anda tahu bahwa Anda semakin tua ketika orang tua Anda mulai mengecewakan Anda, bukannya Anda mengecewakan mereka."
    "Manusia dirancang untuk belajar melalui pengalaman namun sistem pendidikan telah berhasil sehingga kita tidak mendapatkan pengalaman.",
    "Dengan berfokus pada berkedip, Anda berkedip lebih lambat ... Sama untuk bernapas.",
    "Pengemudi terburu-buru untuk mengalahkan lalu lintas biasanya menyebabkan kecelakaan yang menciptakan lalu lintas yang mereka coba hindari.",
    "Karakter yang menikah dalam fiksi secara harfiah dibuat untuk satu sama lain."
    "Bayi adalah hard drive bersih yang dapat diprogram dengan bahasa apa pun.",
    "Mungkin ada obat ajaib yang menyembuhkan setiap penyakit kepada manusia, yang tidak akan pernah kita ketahui karena tidak bekerja pada tikus.",
    "Badak berevolusi untuk menumbuhkan tanduk untuk perlindungan, tapi itulah yang membuat mereka punah."
    "Mungkin kita tidak menemukan pelancong waktu karena kita semua mati dalam 25-50 tahun.",
    "Tidur adalah versi uji coba kematian, Bahkan dilengkapi dengan iklan berdasarkan aktivitas Anda.",
    "Hal yang paling tidak realistis tentang film Spy adalah seberapa bersih sistem ventilasi udara!",
    "Dalam permainan kami bermain melalui mode mudah untuk membuka mode keras. Dalam hidup kita bermain melalui mode keras untuk membuka mode mudah.",
    "Orang-orang yang diam tampak lebih pintar dari orang-orang keras, karena mereka menyimpan pikiran bodoh mereka untuk diri mereka sendiri."
    "Jika Greenland benar-benar berubah hijau, kita semua kacau."
    "Jika seseorang mengatakan hal-hal pintar dalam mimpi Anda, itu benar-benar menunjukkan kepandaian Anda sendiri."
    "Kutipan film terkenal dikreditkan kepada aktor dan bukan penulis yang sebenarnya yang menulisnya.",
    "Tidak ada yang benar-benar mengajari Anda cara mengendarai sepeda. Mereka hanya hype Anda sampai Anda bekerja itu."
    "Tanyakan pada diri sendiri mengapa otak mengabaikan yang kedua.",
    "Anda mungkin lupa tentang 80% dari seluruh hidup Anda dan sebagian besar kenangan yang Anda ingat tidak terlalu akurat dengan apa yang sebenarnya terjadi.",
    "Akan jauh lebih sulit bagi anak-anak untuk menang melawan orang tua mereka di video game di masa depan.",
    "Setiap orang memiliki kekurangan, jika Anda tidak mengenali Anda, Anda memiliki yang baru."
    "Membesarkan anak melatih penggantimu.",
    "'O'pen dimulai dengan lingkaran tertutup, dan 'C'lose dimulai dengan lingkaran terbuka.",
    "Selalu ada seseorang yang membencimu tanpa alasan, dan masih melakukannya.",
    "Setelah popcorn ditemukan, pasti ada banyak biji acak yang dipanggang untuk melihat apakah itu akan memiliki efek yang sama.",
    "Semakin penting tidur nyenyak adalah, semakin sulit untuk tertidur."
    "Berbahakarlah mereka yang dapat menggambarkan dengan benar jenis potongan rambut yang mereka inginkan untuk stylist baru.",
    "Terlalu banyak orang menghabiskan uang yang belum mereka peroleh, untuk membeli hal-hal yang tidak mereka inginkan, untuk mengesankan orang-orang yang tidak mereka sukai!",
    "Karyawan taman hiburan harus pandai menceritakan perbedaan antara jeritan horor dan kegembiraan.",
    "6 hingga 6:30 terasa lebih setengah jam dari 5:50 hingga 6:20",
    "Mendapatkan kata sandi Anda tepat pada upaya login terakhir sebelum penguncian adalah hal terdekat untuk melucuti bom pada menit terakhir yang sebagian besar dari kita akan alami.",
    "Mendengarkan podcast sebelum tidur adalah versi dewasa dari story-time.",
    "Jika semua penjahat berhenti merampok maka industri keamanan akan jatuh di mana mereka kemudian dapat dengan mudah kembali merampok."
    "Satu ton paus benar-benar hanya seperti setengah paus."
    "Ketika Anda menjadi tua, yang lama Anda secara teknis adalah Anda yang baru, dan diri muda Anda adalah yang lama Anda."
    "Anda mungkin tidak akan menemukan banyak ulasan negatif dari parasut di Internet.",
    "Kami menunjukkan cinta dan kekaguman yang paling besar bagi orang-orang ketika mereka tidak lagi ada untuk menghargainya.",
    "Kami telah berlatih tidur ribuan kali, namun tidak bisa melakukannya dengan sangat baik atau konsisten.",
    "Manusia lebih antusias untuk pindah ke planet lain dengan lingkungan yang bermusuhan daripada melestarikan bumi - planet tempat mereka dibentuk dengan sempurna.",
    "Tahap paling bahagia dari kehidupan kebanyakan orang adalah ketika otak mereka belum sepenuhnya berkembang.",
    "Jam alarm yang paling efektif adalah kandung kemih penuh.",
    "Anda mungkin hanya disinkronkan berkedip dengan jutaan orang."
    "Karena kita menguji obat pada hewan terlebih dahulu, obat tikus harus bertahun-tahun lebih cepat dari obat manusia.",
    "Malam sebelum hari libur lebih memuaskan daripada hari libur yang sebenarnya.",
    "Kami menaruh kertas dalam folder untuk menjaganya dari pelipatan.",
    "Di suatu tempat, dua sahabat bertemu untuk pertama kalinya."
    "Otak kita secara bersamaan membenci kita, mencintai kita, tidak peduli pada kita, dan micromanages setiap gerakan kita."
    "Menjadi laki-laki adalah masalah kelahiran. Menjadi seorang pria adalah masalah usia. Tapi menjadi seorang pria adalah masalah pilihan."
    "Segera orang tua akan menyembunyikan akun sosial mereka dari anak-anak mereka daripada anak-anak menyembunyikan akun mereka dari orang tua.",
    "Wikipedia adalah apa yang dimaksudkan internet.",
    "Taman hiburan adalah satu-satunya tempat anda dapat mendengar teriakan di kejauhan dan tidak khawatir.",
    "Pengisi daya telepon nirkabel menawarkan lebih sedikit kebebasan bergerak daripada yang berkabel.",
    "Jika Anda berulang kali mengkritik seseorang karena menyukai sesuatu yang tidak Anda sukai, mereka tidak akan berhenti menyukainya. Mereka akan berhenti menyukaimu."
    "Di suatu tempat ada seorang nenek, yang cucunya benar-benar adalah anak laki-laki paling tampan di dunia."
    "Jika suatu hari nanti teleportasi manusia menjadi nyata, orang masih akan terlambat bekerja."
    "Manusia pertama yang makan kepiting pasti benar-benar lapar untuk mencoba dan memakan laba-laba laut lapis baja",
    "Melakukan sesuatu saja agak menyedihkan, tapi melakukannya solo itu keren af.",
    "Otakmu tiba-tiba menjadi sempurna dalam mengoreksi setelah kau memposting sesuatu.",
    "Selalu ada satu lagu di daftar putar yang selalu Anda lewati tetapi tidak pernah dihapus.",
    "Anak-anak abad berikutnya mungkin akan membenci kita karena mengambil semua nama pengguna yang baik.",
    "Gelembung adalah untuk memancing apa hujan bagi manusia."
    "Semakin banyak orang yang Anda temui, semakin Anda menyadari dan menghargai seberapa baik orang tua Anda membesarkan Anda."
    "Koma adalah jeda singkat, koma adalah jeda yang panjang.",
    "Suatu hari nanti kau tidak akan bangun atau tidak tidur."
    "Segitiga Bermuda mungkin portal keluar dari simulasi ini.",
    "Jika kita menempatkan panel surya di atas tempat parkir, maka mobil kita tidak akan menjadi panas dan kita akan memiliki banyak energi bersih.",
)
