TRUTH = (
    "Apakah Anda seseorang hantu?"
    "Apakah Anda pernah berjalan di pada orang tua Anda melakukan 'itu'?",
    "Siapa orang terakhir yang paling kau sukai? Mengapa?",
    "Apakah Anda pernah diskors dari sekolah?",
    "Jika Anda harus memilih antara telanjang atau memiliki pikiran Anda muncul dalam gelembung pemikiran di atas kepala Anda untuk dibaca semua orang, yang akan Anda pilih?",
    "Apa satu hal yang anda takut untuk kalah?",
    "Apakah Anda menyukai seseorang pada saat ini?",
    "Satu hal tentang sahabatmu yang kau cemburui?",
    "Maukah kau selingkuh dari pacarmu untuk orang kaya?",
    "Apa giliran terbesar Anda?",
    "Kapan terakhir kali kau berbohong pada orang tuamu dan mengapa?",
    "Jelaskan pasangan ideal Anda.",
    "Apa hal paling menakutkan yang pernah kau lakukan?",
    "Apakah Anda pernah memilih hidung Anda dan memakannya?",
    "Kapan terakhir kali kau berbohong pada orang tuamu dan mengapa?",
    "Apakah Anda pernah berbohong tentang usia Anda untuk berpartisipasi dalam kontes?",
    "Apakah Anda pernah tertangkap memeriksa seseorang?",
  
)

DARE = (
    "Tampilkan foto paling memalukan di ponsel Anda"
    "Tampilkan lima orang terakhir yang Anda sms dan apa yang dikatakan pesan",
    "Biarkan sisa grup DM seseorang dari akun Instagram Anda",
    "Makan sepotong bawang putih mentah",
    "Lakukan 100 squat",
    "Simpan tiga es batu di mulutmu sampai meleleh",
    "Katakan sesuatu yang kotor kepada orang di sebelah kiri AndaAnda punya perusahaan!",
    "Berikan pijat kaki kepada orang di sebelah kanan Anda",
    "Masukkan 10 cairan yang tersedia ke dalam cangkir dan minumlah",
    "*Teriaklah kata pertama yang terlintas dalam pikiranmu",
    "Berikan tarian pangkuan untuk seseorang pilihanmu",
    "Buang empat item pakaian",
    "Seperti 15 posting pertama di umpan berita Facebook Anda",
    "Makan sesendok mustard",
    "Tutup matamu sampai kau pergi lagi",
    "Kirim sext ke orang terakhir di buku telepon Anda",
    "Pamerkan wajah orgasmemu",
    "Menggoda makan pisang",
    "Kosongkan dompet / dompet Anda dan tunjukkan kepada semua orang apa yang ada di dalamnya",
    "Lakukan merangkak seksi terbaik anda",
    "Berpura-pura menjadi orang di sebelah kanan anda selama 10 menit",
    "Makan camilan tanpa menggunakan tangan Anda",
    "Katakan dua hal jujur tentang orang lain dalam kelompok",
    "Twerk sebentar",
    "Cobalah dan membuat kelompok tertawa secepat mungkin",
    "Cobalah untuk meletakkan seluruh tinju Anda di mulut Anda",
    "Ceritakan kepada semua orang kisah memalukan tentang dirimu",
    "Cobalah untuk menjilat siku Anda",
    "Posting selfie tertua di ponsel Anda di Instagram Stories",
    "Ceritakan kisah paling menyedihkan yang kau tahu",
    "Howl seperti serigala selama dua menit",
    "Menari tanpa musik selama dua menit",
    "Pole dance dengan tiang imajiner",
    "Biarkan orang lain menggelitik Anda dan mencoba untuk tidak tertawa",
    "Masukkan makanan ringan sebanyak mungkin ke dalam mulutmu sesegera mungkin",
    "Kirim selfie terbaru anda.",
    "Kirim selfie terjelekmu.",
    "Kirim tangkapan layar riwayat pencarian facebook Anda",
    "Kirim tangkapan layar galeri Anda.",
    "Kirim tangkapan layar kotak masuk messenger Anda",
    "Katakan sesuatu yang sangat intim.",
    "Kirim tangkapan layar kotak masuk twitter Anda",
    "Kirim tangkapan layar dari homescreen Anda.",
    "Kirimkan cover lagu kesukaanmu. 🎤",
    "Lakukan lelucon lirik pada seseorang dan kirim bukti.",
    "Mengaku naksir anda saat ini. ❤️",
    "Deklarasikan siapa cinta sejatimu.",
    "Kirim tangkapan layar galeri Anda.",
    "Atur gambar naksirmu sebagai dp-nya.",
    "Sarankan aku lebih berani.",
)
